### PR TITLE
- update to the latest t-engine version

### PR DESCRIPTION
**Pull request by dgradecak**
- use "targetMediaType": "alfresco-metadata-embed"

### CODE REVIEW

**Comment by aborroy** [comment]
Thanks for your contribution!

**Comment by ym85-cmd** [comment]
Hi, can I have the ContentMetadataEmbedder class?

**Comment by aborroy** [comment]
I don't know what you mean. Review installation process: https://github.com/aborroy/alf-tengine-ocr?tab=readme-ov-file#deployment-with-acs-stack

`embed-metadata-action.jar` module is required to be deployed in Alfresco Repository.

**Comment by ym85-cmd** [comment]
Yes, I installed the OCR action, and it works well in Alfresco ACS. However, the action is not accessible within the Records Management (RM) module. Could you guide me on how to make the action available in RM?

**Comment by aborroy** [comment]
Did you install the OCR Share Action?

https://github.com/aborroy/alf-tengine-ocr/tree/master/ocr-share-action

Here is the JAR artifact: https://github.com/aborroy/alf-tengine-ocr/tree/master/docker/share/modules/jars

**Comment by ym85-cmd** [comment]
Yes

Le lun. 16 déc. 2024, 11:41, Angel Borroy ***@***.***> a
écrit :

**Pull request merged**
